AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  s1_collect_time

  Sample SAM Template for s1_collect_time

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300

Parameters:
  DatasetBucketName:
    Type: String

Resources:
  DatasetBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DatasetBucketName
  CreateDatasetFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: s1_collect_time/
      Handler: create_collection.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      MemorySize: 10240
      Environment:
        Variables:
          DatasetBucketName: !Ref DatasetBucketName
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref DatasetBucketName
      Events:
        DailyCreate:
          Type: Schedule
          Properties:
            Schedule: 'cron(0 12 * * ? *)'
  FindCollectFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: s1_collect_time/
      Handler: app.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      MemorySize: 10240
      Environment:
        Variables:
          DatasetBucketName: !Ref DatasetBucketName
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref DatasetBucketName
      Events:
        FindCollect:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /s1-collect-info/{interface}
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  FindCollectApi:
    Description: "API Gateway endpoint URL for Prod stage for Find Collect function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  FindCollectFunction:
    Description: "Find Collect Lambda Function ARN"
    Value: !GetAtt FindCollectFunction.Arn
  FindCollectIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt FindCollectFunctionRole.Arn
